### ISSUE TITLE
Un peu de triche..

### ISSUE THREAD

**Issue by cbjims** [damienbeaufils/clean-architecture-demo#2]
Merci pour ce projet.
Je cherchais un moyen pour utiliser la clean archi avec JpaRepository.
Il me semble que la façon dont tu l'as fais n'est pas totalement clean archi.
Ton Repo a des méthodes qui correspondent exactement aux noms des méthodes du JpaRepository.
Si je change le findAll et décide de le nommer "findAllDummies" ça ne marchera plus je pense (pas testé)
Du coup il y a une dépendance domain => infra 
Non ?

**Comment by damienbeaufils** [comment]
Hello,

Merci pour cette question.

Effectivement, les méthodes du repository déclarées dans le domaine ont le même nom que les méthodes classiques du JpaRepository : c'est voulu, dans le sens où le nom des méthodes me convient car portent le sens métier que je souhaite faire porter au repository, vu la simplicité du métier exprimé dans cet exemple. Je comprends que ça peut être considéré comme de la triche :)

Si tu changes le nom de la méthode dans le domain, il faut effectivement changer l'implémentation dans l'infra, pour faire un mapping par exemple. C'est normal et voulu. Et c'est bien une dépendance infrastructure => domain et non domain => infra : à aucun moment tu as des imports de l'infrastructure dans le domain. L'infrastructure est impactée par les évolutions du domain, mais le domain ne doit pas être impacté par les évolutions de l'infrastructure. 
En effet, si le métier de l'application vient à évoluer, et que de fait le domain change, il est normal de faire évoluer la couche Adapter de l'infrastructure. C'est le contraire qui aurait été gênant : si on décide finalement qu'on ne veut plus de Spring Data JPA ou bien qu'on passe sur une couche de persistence en fichier par exemple, seule l'implémentation de l'infrastructure doit être modifiée, et à aucun moment on ne doit toucher au domain. C'est un des intérêts de la Clean Archi.

Est-ce que cela répond à ton interrogation ?

**Comment by cbjims** [comment]
Merci pour la  réponse, je comprends que ca marche bien dans ton cas car les noms de méthodes correspondent aux besoins métier.

Concernant le coté dépendance je suis pas tout à fait d'accord.
C'est vrai qu'il n'y a pas d'import de l'infra dans le domain mais ce qui me gène c'est que un simple refacto du nom de la méthode dans le repo du domain casserai l'application.
C'est un peu fourbe à mon sens.

**Comment by damienbeaufils** [comment]
Je comprends ton point, bien que le domain ne dépende pas de l'infra, un renommage aurait un impact sur l'application, ce que tu n'aurais pas si les noms étaient complètement dissociés. Heureusement les tests sont là pour mitiger la chose en te donnant un feedback rapide sur l'état de l'application avant même que tu ne la lances.

**Comment by cbjims** [comment]
Merci pour tes réponses
